config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/leaderboards'
  post 'quiz/answered', to: 'quiz#answered'
  get 'welcome/profile'

  get 'quiz/sports'
  get 'quiz/music'
  get 'quiz/entertainment'
  get 'quiz/science'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :questions

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def show
		begin
			@question = Question.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to questions_path
		end
	end

	def index
		@questions = Question.all
	end


	def new
	end

	def create
		@question = Question.new(question_params)

		@question.save
		redirect_to @question
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy

		redirect_to questions_path
	end


	private
		def question_params
			params.require(:question).permit(:question, :answer, :category)
		end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
	skip_before_action :verify_authenticity_token
	def sports
		@question = Question.where(category: "Sports").order(Arel.sql('RANDOM()')).first
	end

	def music
		@question = Question.where(category: "Music").order(Arel.sql('RANDOM()')).first
	end

	def entertainment
		@question = Question.where(category: "Entertainment").order(Arel.sql('RANDOM()')).first
	end

	def science
		@question = Question.where(category: "Science").order(Arel.sql('RANDOM()')).first
	end

	def answered
		current_user.score += 4 if params[:correct]
		current_user.score -= 1 if params[:wrong]
		current_user.save
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:profile]
  def index
  end
  def leaderboards
  	@Users = User.limit(10).order(score: :desc)
  end
  
  def profile
  	@User = current_user
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivial Trivia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>Questions</h1>
<table>
	<tr>
		<th>Question</th>
		<th>Answer</th>
		<th>Category</th>
	</tr>

	<% @questions.each do |question| %>
		<tr>
			<td><%= question.question %></td>
			<td><%= question.answer %></td>
			<td><%= question.category %></td>
			<td><%= link_to 'Show', question_path(question) %></td>
			<td><%= link_to 'Delete', question_path(question), method: :delete, data: {
				confirm: 'Are you sure you want to delete this question?'
			} %></td>

		</tr>
	<% end %>
</table>

<%= link_to 'Back to Home Page', "/welcome/index" %>

app/views/questions/new.html.erb
<body  class="questions">
  <h1 class="question_header">Upload your own trivia questions</h1>
  <%= form_with scope: :question, url: questions_path,  local: true do |form| %>
    <p class="question">
      <%= form.label :question %><br>
      <%= form.text_field :question %>
    </p>
   
    <p class="answer">
      <%= form.label :answer %><br>
      <%= form.text_field :answer %>
    </p>

    <p class="category">
      <%= form.label :category %><br>
      <%= form.select(:category, options_for_select([['Sports','Sports'],['Entertainment','Entertainment'],['Music','Music'],['Science','Science']])) %>
    </p>
   
    <p class="submit">
      <%= form.submit %>
    </p>
  <% end %>
</body>

app/views/questions/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>
 
<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>
<p>
	<strong>Category:</strong>
	<%= @question.category %>
</p>
<%= link_to "Back to Home Page", '/welcome/index' %>
<%= link_to 'Create Another Question', action: 'new', controller: 'questions' %>

app/views/quiz/_table.html.erb
<li id="<%= @question.id %>" style="display:block">
	<p><%= @question.question %></p>
	<div>
		<%= text_field_tag "text-content-#{@question.id}", "" %>
		<%= submit_tag 'Answer', :onclick =>"alerts('text-content-#{@question.id}', '#{@question.answer}')" %>
	</div>
</li>
<%= link_to 'Back to Home Page', "/welcome/index" %>

app/views/quiz/entertainment.html.erb
<h1> You know some entertainment</h1>
<%= render "quiz/table" %>

app/views/quiz/music.html.erb
<h1>You know some Music? </h1>
<%= render "quiz/table" %>

app/views/quiz/science.html.erb
<h1> You know your science</h1>
<%= render "quiz/table" %>

app/views/quiz/sports.html.erb
<h1> You know your sports?</h1>
<%= render "quiz/table" %>

app/views/welcome/index.html.erb
<div class="header">
	<h1>Trivial Trivia</h1>
	<!--<img src="images/TrivaPic.jpg">-->
	<h2>A fun trivia website</h2>
</div>

<ul>
	<li><%= link_to 'Home', controller: 'welcome' %></li>
	<li><%= link_to 'Create Questions', action: 'new', controller: 'questions' %></li>
	<li><%= link_to 'Leaderboards', action: 'leaderboards', controller: 'welcome' %></li>
	<% if current_user %>
	<li style="float: right"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
	<li style="float: right"><%= link_to 'Profile', action: 'profile', controller: 'welcome' %></li>
	<% else %>
	<li style="float: right"><%= link_to 'Sign In', new_user_session_path %></li>
	<li style="float: right"><%= link_to 'Sign Up', new_user_registration_path %></li>
	<% end %>
</ul>

<div class="category-grid">
	<%= link_to action: "sports", controller: 'quiz', :class=>"grid-element" do %>
		<%= image_tag 'sports.png', :class=>"grid-element" %>
	<% end %>
	<%= link_to action: "music", controller: 'quiz', :class=>"grid-element" do %>
		<%= image_tag('music.png', :class=>"grid-element") %>
	<% end %>
	<%= link_to action: "entertainment", controller: 'quiz', :class=>"grid-element" do %>
		<%= image_tag('entertainment.png', :class=>"grid-element") %>
	<% end %>
	<%= link_to action: "science", controller: 'quiz', :class=>"grid-element" do %>
		<%= image_tag('science.png', :class=>"grid-element") %>
	<% end %>
</div>

app/views/welcome/leaderboards.html.erb
<h1> Leaderboard</h1>
<table>
	<tr>
		<th>Username</th>
		<th>Score</th>
	</tr>

	<% @Users.each do |user| %>
		<tr>
			<td><%= user.email %></td>
			<td><%= user.score %></td>

		</tr>
	<% end %>
</table>
<%= link_to 'Home', '/' %>

app/views/welcome/profile.html.erb
<h1 class="profile-header"><%= @User.email %>'s Page</h1>
<p class="profile-p">Your score is <%= @User.score %></p>